// Shared control definitions keep validation, defaults and UI ranges consistent.
export const OPTIONS = {
  Sky: {
    skyEnabled: ["Sky enabled", true],
    skyAutomatic: ["Automatic palette", true],
    skyIntensity: ["Sky intensity", 1, 0.1, 3],
    zenithColor: ["Zenith colour", "#3978bc"],
    horizonColor: ["Horizon colour", "#b6cbd9"],
    horizonWarmth: ["Horizon warmth", 0.3, 0, 1],
    turbidity: ["Turbidity", 2.2, 1, 8],
    sunDiscSize: ["Sun disc degrees", 0.6, 0.1, 2],
    sunGlow: ["Sun glow", 0.45, 0, 2],
    cloudsEnabled: ["Clouds", false],
    cloudAmount: ["Cloud amount", 0.16, 0, 0.7],
  },
  Lighting: {
    brakeLightsEnabled: ["Brake light spill", true],
    brakeLightIntensity: ["Brake light power", 1.5, 0, 5],
    brakeLightDistance: ["Brake light reach", 2.5, 0.5, 6],
    sunIntensity: ["Sun intensity", 1.35, 0.5, 2],
    sunElevation: ["Sun elevation", 30, 2, 75],
    sunAzimuth: ["Sun azimuth", 225, 0, 360],
    automaticSunColor: ["Automatic sun colour", true],
    sunColor: ["Sun colour", "#ffe3ba"],
    ambientIntensity: ["Ambient fill", 0.85, 0.1, 1.8],
    ambientColor: ["Sky fill", "#b9d0eb"],
    groundColor: ["Ground fill", "#aaa294"],
    environmentEnabled: ["Environment", true],
    environmentIntensity: ["Environment intensity", 0.6, 0, 2],
    environmentQuality: [
      "Environment quality",
      "medium",
      ["low", "medium", "high"],
    ],
  },
  Shadows: {
    shadowQuality: [
      "Shadow quality",
      "medium",
      ["off", "low", "medium", "high"],
    ],
    shadowDistance: ["Coverage", 30, 15, 200],
    adaptiveShadows: ["Adaptive coverage", true],
    shadowForward: ["Forward bias", 0.4, 0, 0.9],
    shadowSoftness: ["Softness", 3, 0, 4],
    shadowStrength: ["Shadow strength", 0.68, 0, 1],
    shadowBias: ["Bias", -0.0001, -0.002, 0.002],
    shadowNormalBias: ["Normal bias", 0.015, 0, 0.1],
    nativeCSMTuning: ["Native CSM tuning", true],
  },
  Materials: {
    surfaceWarmth: ["Architecture warmth", 0.2, 0, 1],
    materialDetail: ["Procedural roughness", true],
    carReflection: ["Car reflection", 1, 0, 2],
    roadRoughness: ["Road roughness", 0.85, 0.65, 1],
    materialOverrides: ["Material overrides", {}],
  },
  Atmosphere: {
    volumetricEnabled: ["Volumetric sunlight", false],
    volumetricStrength: ["Volumetric strength", 0.08, 0, 0.3],
    volumetricDensity: ["Volumetric density", 0.008, 0, 0.03],
    volumetricDecay: ["Volumetric decay", 0.96, 0.8, 1],
    volumetricSamples: ["Volumetric samples", 8, 4, 16],
    volumetricMaxDistance: ["Volumetric max distance", 80, 10, 200],
    atmosphereEnabled: ["Aerial perspective", true],
    atmosphereStrength: ["Atmosphere strength", 0.13, 0, 1],
    atmosphereStart: ["Start distance", 80, 5, 500],
    atmosphereSunWarmth: ["Sun warmth", 0.25, 0, 1],
    fogEnabled: ["Fallback fog", false],
    fogStrength: ["Fog strength", 0.12, 0, 1],
  },
  "Post Processing": {
    postEnabled: ["Post processing", true],
    gradeEnabled: ["Colour grade", true],
    exposure: ["Exposure", 1.08, 0.7, 1.4],
    contrast: ["Contrast", 1.045, 0.8, 1.2],
    saturation: ["Saturation", 1.02, 0.7, 1.3],
    vibrance: ["Vibrance", 0.08, -0.2, 0.4],
    temperature: ["Temperature", 0.015, -0.15, 0.15],
    tint: ["Tint", 0, -0.1, 0.1],
    shadowLift: ["Shadow lift", 0.004, 0, 0.1],
    highlightCompression: ["Highlight shoulder", 0.04, 0, 0.3],
    blackLevel: ["Black level", 0.003, 0, 0.06],
    whiteLevel: ["White level", 1, 0.8, 1.2],
    vignetteStrength: ["Vignette", 0.035, 0, 0.2],
    vignetteSoftness: ["Vignette softness", 0.7, 0.3, 1],
    aoEnabled: ["Contact AO", true],
    aoQuality: ["AO quality", "low", ["low", "medium", "high"]],
    aoStrength: ["AO strength", 0.3, 0, 1],
    aoRadius: ["AO radius", 0.8, 0.1, 3],
    aoBias: ["AO bias", 0.04, 0.005, 0.2],
    sunRaysEnabled: ["Sun rays", true],
    sunRayStrength: ["Sun ray strength", 0.14, 0, 1],
    sunRayDecay: ["Sun ray decay", 0.96, 0.8, 0.995],
    sunRayDensity: ["Sun ray density", 0.8, 0.2, 1.2],
    sunRayExposure: ["Sun ray exposure", 0.5, 0, 2],
    lensFlareEnabled: ["Lens flare", true],
    lensFlareStrength: ["Lens flare strength", 0.32, 0, 1],
    flareGhostStrength: ["Ghost strength", 0.65, 0, 1],
    flareIridescence: ["Iridescence", 0.65, 0, 1],
    flareStreakStrength: ["Streak strength", 0.12, 0, 1],
    bloomEnabled: ["Bloom", true],
    bloomThreshold: ["Bloom threshold", 1.5, 0.5, 5],
    bloomStrength: ["Bloom strength", 0.055, 0, 0.3],
    bloomRadius: ["Bloom radius", 1.2, 0.5, 3],
    postQuality: ["Post quality", "medium", ["off", "low", "medium", "high"]],
    fxaaEnabled: ["FXAA", true],
    sharpenEnabled: ["Sharpen", false],
    sharpenStrength: ["Sharpen strength", 0.08, 0, 0.3],
  },
  Quality: {
    renderScale: ["Render scale", 1, 1, 1.5],
    sceneSamples: ["Scene MSAA", "auto", ["auto", "0", "2", "4"]],
  },
  Debug: {
    debugProfile: ["Per-pass profiling (diagnostic only)", false],
    debugEnabled: ["Detailed diagnostics", false],
    debugView: [
      "Render view",
      "final",
      [
        "final",
        "depth",
        "ao",
        "bloom",
        "sun-position",
        "sun-visibility",
        "sun-rays",
        "volumetric",
      ],
    ],
  },
};
export const OPTION_DEFINITIONS = Object.freeze(
  Object.assign({}, ...Object.values(OPTIONS)),
);
export const OPTION_DEFAULTS = Object.freeze(
  Object.fromEntries(
    Object.entries(OPTION_DEFINITIONS).map(([k, v]) => [k, v[1]]),
  ),
);
export const MATERIAL_KINDS = [
  "road",
  "grass",
  "concrete",
  "barrier",
  "car",
  "metal",
  "tire",
  "glass",
  "marking",
  "signage",
  "emissive",
  "architecture",
  "other",
  "ignore",
];
