import { OPTION_DEFAULTS } from "./options.js";
export const PRESET_IDS = Object.freeze([
  "vanilla",
  "clear-day",
  "overcast",
  "cinematic-lite",
  "cinematic",
  "recording",
]);

export const PRESET_LABELS = Object.freeze({
  vanilla: "Vanilla",
  "clear-day": "Clear Day",
  overcast: "Soft Overcast",
  "cinematic-lite": "Golden Hour Lite",
  cinematic: "Golden Hour",
  recording: "Golden Hour Capture",
});

export const SHADOW_MAP_SIZES = Object.freeze({
  off: 0,
  low: 1024,
  medium: 2048,
  high: 4096,
});

export const PRESETS = Object.freeze({
  vanilla: Object.freeze({
    ...OPTION_DEFAULTS,
    sunIntensity: 1,
    sunElevation: 30,
    sunAzimuth: 225,
    sunColor: "#ffe3ba",
    ambientIntensity: 1,
    ambientColor: "#a9c9f1",
    exposure: 1,
    fogEnabled: false,
    fogStrength: 0.2,
    shadowQuality: "off",
    carContactShadowEnabled: false,
    renderScale: 1,
    surfaceWarmth: 0.2,
    shadowDistance: 30,
    shadowSoftness: 4,
  }),
  "clear-day": Object.freeze({
    ...OPTION_DEFAULTS,
    skyAutomatic: false,
    zenithColor: "#398cc4",
    horizonColor: "#c4dfeb",
    horizonWarmth: 0.05,
    cloudsEnabled: true,
    cloudAmount: 0.16,
    sunElevation: 55,
    sunAzimuth: 220,
    automaticSunColor: false,
    sunColor: "#fff1d6",
    sunIntensity: 1.25,
    ambientIntensity: 0.78,
    ambientColor: "#c6dbed",
    groundColor: "#a29a8c",
    shadowStrength: 0.78,
    shadowQuality: "medium",
    shadowDistance: 30,
    shadowSoftness: 3,
    exposure: 1.04,
    contrast: 1.05,
    saturation: 1.05,
    temperature: 0,
    aoQuality: "medium",
    aoStrength: 0.38,
    motionBlurEnabled: true,
    motionBlurExposureMs: 20,
    motionBlurMaxPixels: 32,
    bloomStrength: 0.025,
    lensFlareStrength: 0.14,
    flareGhostStrength: 0.25,
    flareIridescence: 0.2,
    flareStreakStrength: 0.06,
    sunRaysEnabled: false,
    volumetricEnabled: false,
    renderScale: 1,
  }),
  overcast: Object.freeze({
    ...OPTION_DEFAULTS,
    skyAutomatic: false,
    zenithColor: "#8ba7b9",
    horizonColor: "#d2d8d9",
    horizonWarmth: 0,
    skyIntensity: 0.86,
    cloudsEnabled: true,
    cloudAmount: 0.66,
    sunElevation: 44,
    sunAzimuth: 220,
    automaticSunColor: false,
    sunColor: "#e4ebf0",
    sunIntensity: 0.72,
    sunGlow: 0.06,
    sunDiscSize: 0.2,
    ambientIntensity: 1.08,
    ambientColor: "#c9d5df",
    groundColor: "#a9adb0",
    shadowStrength: 0.42,
    shadowQuality: "medium",
    shadowDistance: 30,
    shadowSoftness: 4,
    exposure: 1.08,
    contrast: 1.03,
    saturation: 0.89,
    temperature: -0.025,
    aoQuality: "medium",
    aoStrength: 0.38,
    motionBlurEnabled: true,
    motionBlurExposureMs: 20,
    motionBlurMaxPixels: 32,
    bloomEnabled: false,
    sunRaysEnabled: false,
    lensFlareEnabled: false,
    volumetricEnabled: false,
    renderScale: 1,
  }),
  "cinematic-lite": Object.freeze({
    ...OPTION_DEFAULTS,
    sunIntensity: 1.45,
    sunElevation: 30,
    sunAzimuth: 225,
    sunColor: "#ffe3ba",
    ambientIntensity: 0.9,
    ambientColor: "#a9c9f1",
    exposure: 1.08,
    fogEnabled: false,
    fogStrength: 0.12,
    shadowQuality: "low",
    renderScale: 1,
    sunRaysEnabled: false,
    lensFlareEnabled: false,
    volumetricEnabled: false,
    aoEnabled: false,
    bloomEnabled: false,
    materialDetail: false,
    vignetteStrength: 0,
    environmentQuality: "low",
    postQuality: "low",
    surfaceWarmth: 0.2,
    shadowDistance: 30,
    shadowSoftness: 4,
  }),
  cinematic: Object.freeze({
    ...OPTION_DEFAULTS,
    cloudsEnabled: true,
    cloudAmount: 0.44,
    sunIntensity: 1.28,
    sunElevation: 26,
    sunAzimuth: 225,
    sunColor: "#ffe3ba",
    ambientIntensity: 0.65,
    ambientColor: "#a9c9f1",
    exposure: 1.06,
    fogEnabled: false,
    fogStrength: 0.2,
    shadowQuality: "medium",
    renderScale: 1,
    surfaceWarmth: 0.2,
    shadowDistance: 30,
    shadowSoftness: 4,
    sunRaysEnabled: true,
    sunRayStrength: 0.34,
    aoQuality: "medium",
    lensFlareEnabled: true,
    lensFlareStrength: 0.32,
    flareGhostStrength: 0.55,
    flareIridescence: 0.65,
    flareStreakStrength: 0.12,
    motionBlurEnabled: true,
    motionBlurExposureMs: 20,
    motionBlurMaxPixels: 32,
    volumetricEnabled: false,
  }),
  recording: Object.freeze({
    ...OPTION_DEFAULTS,
    cloudsEnabled: true,
    cloudAmount: 0.44,
    sunIntensity: 1.28,
    sunElevation: 26,
    sunAzimuth: 225,
    sunColor: "#ffe3ba",
    ambientIntensity: 0.65,
    ambientColor: "#a9c9f1",
    exposure: 1.06,
    fogEnabled: false,
    fogStrength: 0.22,
    shadowQuality: "medium",
    renderScale: 1,
    sunRaysEnabled: true,
    sunRayStrength: 0.4,
    lensFlareEnabled: true,
    lensFlareStrength: 0.46,
    flareGhostStrength: 0.75,
    flareIridescence: 0.75,
    flareStreakStrength: 0.17,
    volumetricStrength: 0.1,
    volumetricSamples: 12,
    volumetricDensity: 0.008,
    aoQuality: "high",
    environmentQuality: "high",
    postQuality: "high",
    sharpenEnabled: false,
    fxaaEnabled: true,
    volumetricEnabled: true,
    motionBlurEnabled: true,
    motionBlurExposureMs: 20,
    motionBlurMaxPixels: 32,
    surfaceWarmth: 0.2,
    shadowDistance: 30,
    shadowSoftness: 4,
  }),
});

export const OVERRIDE_LIMITS = Object.freeze({
  sunIntensity: [0.5, 2],
  sunElevation: [10, 75],
  sunAzimuth: [0, 360],
  ambientIntensity: [0.1, 1.8],
  exposure: [0.7, 1.4],
  fogStrength: [0, 1],
  renderScale: [1, 1.5],
  surfaceWarmth: [0, 1],
  shadowDistance: [30, 200],
  shadowSoftness: [0, 4],
});

export function resolvePresetSettings(settings) {
  return {
    ...PRESETS[settings.preset],
    ...settings.overrides,
    enabled: settings.enabled && settings.preset !== "vanilla",
  };
}
